[project]
name = "drdetector"
version = "0.1"
dependencies = [
    "opencv-python==4.10.0.84",
    "pandas==2.2.3",
    "numpy==2.1.3"
]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[projects.scripts]
drdetector = "drdetector:main"